# Generated by Django 5.0.7 on 2024-07-25 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_diurno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfrtDesa',
            fields=[
                ('ofrtdia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='s_diurno.ofrtdia')),
            ],
            bases=('s_diurno.ofrtdia',),
        ),
    ]
