# Generated by Django 5.0.7 on 2024-10-14 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("s_diurno", "0002_ofrtdesa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ofrtdia",
            name="imagen",
        ),
    ]
