# Generated by Django 5.0.7 on 2024-07-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin_log",
            fields=[
                ("nombre", models.CharField(max_length=100)),
                (
                    "username",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("contraseña", models.TextField(max_length=50)),
            ],
        ),
    ]
