# Generated by Django 5.0.7 on 2024-07-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hola", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin_log",
            name="is_autentiqued",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
