# Generated by Django 5.0.7 on 2024-07-24 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebidas',
            fields=[
                ('ofrtterraza_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='terraza.ofrtterraza')),
                ('alcohol', models.DecimalField(decimal_places=2, max_digits=8, max_length=100)),
            ],
            bases=('terraza.ofrtterraza',),
        ),
        migrations.CreateModel(
            name='Helados',
            fields=[
                ('ofrtterraza_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='terraza.ofrtterraza')),
            ],
            bases=('terraza.ofrtterraza',),
        ),
        migrations.CreateModel(
            name='Platos',
            fields=[
                ('ofrtterraza_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='terraza.ofrtterraza')),
            ],
            bases=('terraza.ofrtterraza',),
        ),
    ]
