# Generated by Django 5.0.7 on 2024-07-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
