# Generated by Django 5.0.7 on 2024-10-14 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evento", "0003_alter_reserva_cantidad"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="imagen",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="cantidad",
        ),
    ]
