# Generated by Django 5.0.7 on 2024-07-24 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebidas',
            fields=[
                ('ofrttab_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taberna.ofrttab')),
                
            ],
            bases=('taberna.ofrttab',),
        ),
        migrations.CreateModel(
            name='Specials',
            fields=[
                ('ofrttab_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taberna.ofrttab')),
                ('beneficio', models.TextField()),
            ],
            bases=('taberna.ofrttab',),
        ),
    ]
