# Generated by Django 5.0.7 on 2024-07-24 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0002_bebidas_specials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bebidas',
            old_name='grado_alcohol',
            new_name='alcohol',
        ),
    ]
