# Generated by Django 5.0.7 on 2024-10-14 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taberna", "0004_alter_bebidas_alcohol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bebidas",
            name="alcohol",
        ),
        migrations.RemoveField(
            model_name="ofrttab",
            name="imagen",
        ),
    ]
